remote_theme: pages-themes/slate@v0.2.0
url: https://dustada1.github.io/capstone_blog_test/
header_pages:
 - index.md
 - about.md
 - page3.md
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

